### ISSUE TITLE
[BUG] 테스트 progress bar가 이전 상태를 기억하지 못함

### ISSUE THREAD

**Issue by jhsung23** [dnd-side-project/dnd-10th-3-frontend#102]
## bug 설명

![Feb-15-2024 23-16-17](https://github.com/dnd-side-project/dnd-10th-3-frontend/assets/69228045/b50c5f38-790c-42c2-b76c-51fa16ad8c4f)

프로그레스가 계속 초기화됨

## bug 재현 방법

테스트 실행

## ✅ Issue 등록 전 확인 후 체크해 주세요! (x 표시 해 주세요.)

- [x] Labels을 등록했습니다.

**Comment by CodyMan0** [comment]
해결할게요~
