### ISSUE TITLE
[BUG] 토글탭 동작 이상

### ISSUE THREAD

**Issue by jhsung23** [dnd-side-project/dnd-10th-3-frontend#109]
## bug 설명

![Feb-17-2024 01-35-13](https://github.com/dnd-side-project/dnd-10th-3-frontend/assets/69228045/802d10fe-95b6-4c93-a9c3-e8a6d622acb5)

현재 url 기준으로 토글 설정하는 걸 안넣어서 생긴 버그

## ✅ Issue 등록 전 확인 후 체크해 주세요! (x 표시 해 주세요.)

- [x] Labels을 등록했습니다.

**Comment by CodyMan0** [comment]
아마 전역 상태로 하나 빠져있으면 해결되지 않을까 싶어요~ 예상한 이슈라 버그 리포트가 맞을까요?!

**Comment by jhsung23** [comment]
> 아마 전역 상태로 하나 빠져있으면 해결되지 않을까 싶어요~ 예상한 이슈라 버그 리포트가 맞을까요?!

앗 테스트의 프로그레스 바랑 비슷한 느낌으로 꼭 fix돼야 하는거라 까먹을까봐 버그로 넣어놨어요~ 이슈로 변경할까요?

**Comment by jhsung23** [comment]
> 아마 전역 상태로 하나 빠져있으면 해결되지 않을까 싶어요~ 예상한 이슈라 버그 리포트가 맞을까요?!

예상하셨군요... 저는 몰랐어요 ㅋㅋㅋ 🤪

**Comment by CodyMan0** [comment]
모를 수 있죠!! 아마 제가 더 모르는게 많은데 아마 이부분은 무의식적으로 알고 있었던 것 같아요!!
