### ISSUE TITLE
[FEAT] 돈워리 디자인에 맞춰 디자인 시스템에 적용

### ISSUE THREAD

**Issue by CodyMan0** [dnd-side-project/dnd-10th-3-frontend#47]
## 요구사항
[SYS-1-01]

## 상세 요구사항
디자인 시안에 맞게 다른 디자인 시스템에 사용될 기본 값을 정의해야 합니다. 

## TODO

1. color 
2. gradient
3. typegraphy
4. font 
5. spacing
6. border radius
7. 기본 구조 리팩토링

## 예상 소요 시간
2H , 디자인팀과 협업에 따라 상이할 것 같습니다. 

## ✅ Issue 등록 전 확인 후 체크해 주세요! (x 표시 해 주세요.)

- [x] Assignees(이슈 담당자)를 지정했습니다.
- [x] Labels, Milestone을 등록했습니다.

**Comment by jhsung23** [comment]
spacing도요~!
