### ISSUE TITLE
[BUG] next 환경에서 SVG 컴포넌트 에러

### ISSUE THREAD

**Issue by jhsung23** [dnd-side-project/dnd-10th-3-frontend#54]
## bug 설명

<img width="1185" alt="스크린샷 2024-01-31 오후 9 05 05" src="https://github.com/dnd-side-project/dnd-10th-3-frontend/assets/69228045/287c812a-8ab1-4647-aa5f-065150122ee4">

```
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.
```

Button이나 Input 등 SVG를 컴포넌트로 가져와 렌더링해야 하는 컴포넌트가 페이지에 있을 때 에러가 발생합니다.

## bug 재현 방법

```tsx
import Submit from '@/assets/icons/submit.svg';

export default function Home() {
  return (
    <>
      <Submit />
    </>
  );
}
```

svg를 import하여 jsx 형식으로 사용

## ✅ Issue 등록 전 확인 후 체크해 주세요! (x 표시 해 주세요.)

- [x] Labels을 등록했습니다.

**Comment by CodyMan0** [comment]
svg 파일도 올려주시면 버그 재현할 수 있을 것 같아요!

**Comment by CodyMan0** [comment]
혹시 'use client' 때문일까요?!

**Comment by jhsung23** [comment]
> 혹시 'use client' 때문일까요?!

아뇨 저희가 그때 svgr 패키지 설치는 했는데 next config에 설정을 하지 않아서 생긴 문제더라구요. 곧 PR 올리겠습니다!
