### ISSUE TITLE
[BUG] @toss/use-funnel 훅을 app 라우터에서 사용시 등장하는 모듈 에러 

### ISSUE THREAD

**Issue by CodyMan0** [dnd-side-project/dnd-10th-3-frontend#76]
## bug 설명
<img width="551" alt="스크린샷 2024-02-12 오후 1 46 05" src="https://github.com/dnd-side-project/dnd-10th-3-frontend/assets/93697790/6d355ccd-b5b3-496c-b0ec-3f24d34891d9">
<img width="244" alt="스크린샷 2024-02-12 오후 1 48 12" src="https://github.com/dnd-side-project/dnd-10th-3-frontend/assets/93697790/8bb24e81-96e9-4978-bbf2-125eeb144516">

## bug 재현 방법
1. yarn add @toss-usefunnel 
2. 해당 페이지에서 import 후 구현 

```tsx
const [Funnel, setStep] = useFunnel(['홈', '사전1', '사전2']);

  <Funnel>
      <Funnel.Step name="홈">
...
      </Funnel.Step>
 </Funnel>
```

## 기타 참고사항
app 라우터에서 useFunnel 훅을 사용할 수 없는건지?? 무엇때문인지 확인하려고 합니다. 

## 시도 과정
1. react-query 의존성을 설치하여 위의 에러는 해결했습니다. 
2. nextRouter isn't mounted 에러를 만났습니다. 해당 라이브러리 issue에 등록된 글을 통해 현재 사용하기는 어렵다고 판단했습니다...

## ✅ Issue 등록 전 확인 후 체크해 주세요! (x 표시 해 주세요.)

- [ ] Labels을 등록했습니다.

**Comment by jhsung23** [comment]
page가 기본 서버 컴포넌트라 훅 사용못해서 그럴 것 같아요?!

**Comment by CodyMan0** [comment]
app router에선 next/router -> next/navigation으로 사용해야해서 라이브러리 내부에서 충돌이 일어나네요;;
